# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: db98927b0ace03b515e0e01921e0173cd3c3d45099704e3c854297599483881806400955b334da5be6d1d61fd937521bdef29d3f35676d42093b11d7b94683ca

test:
  secret_key_base: acd4a28c4f0f4878af0a46583e851c42dbd3976be941ee3593d79e489501495203e366adaef3b82641c924cc488267db527b6bc3aceaf69788065ab4ee8767d7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
